ui:
  # @description Host port for the RAG UI. If unspecified, a random available port is assigned. Specify a port number to use a custom value.
  port: ""
  # @hidden
  image: icr.io/ai-services-cicd/rag-ui:v0.0.9

backend:
  # @description Host port for the OpenAI-compatible RAG service. Defaults to unexposed; assign a port to enable external access.
  port: "0"
  # @hidden
  image: icr.io/ai-services-cicd/rag:v0.0.18

ingest:
  # @hidden
  log_level: "INFO"

etcd:
  # @hidden
  image: icr.io/ai-services/etcd:3.6.5-3

minio:
  # @hidden
  image: icr.io/ai-services/minio:RELEASE.2025-10-15T17-29-55Z-3

milvus:
  # @hidden
  image: icr.io/ppc64le-oss/milvus-ppc64le:v2.5.3

instruct:
  # @hidden
  image: icr.io/ibmaiu_internal/ppc64le/dd2/rhaiis:3.2.5-1764185711

embedding:
  # @hidden
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.9.1

reranker:
  # @hidden
  image: icr.io/ibmaiu_internal/ppc64le/dd2/rhaiis:3.2.5-1764185711
