ui:
  port: 3000
  # @hidden
  image: icr.io/ai-services-cicd/rag-ui:v0.0.6

backend:
  # @hidden
  image: icr.io/ai-services-cicd/rag:v0.0.6

etcd:
  # @hidden
  image: icr.io/ai-services-cicd/etcd:3.6.5-1

minio:
  # @hidden
  image: icr.io/ai-services-cicd/minio:RELEASE.2025-10-15T17-29-55Z-1

milvus:
  # @hidden
  image: icr.io/ppc64le-oss/milvus-ppc64le:v2.5.3 

instruct:
  # @hidden
  image: icr.io/ibmaiu_internal/ppc64le/dd2/rhaiis:3.2.5-ci_236 

embedding:
  # @hidden
  image: icr.io/ppc64le-oss/vllm-ppc64le:0.9.1 

reranker:
  # @hidden
  image: icr.io/ibmaiu_internal/ppc64le/dd2/rhaiis:3.2.5-ci_236
